# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Publications
    url: publication/
    weight: 11
  #- name: Talks
  #  url: /#talks
  #  weight: 12
  #- name: News
  #  url: /#news
  #  weight: 13
  - name: Experience
    url: experience/
    weight: 20
  #- name: Projects
  #  url: projects/
  #  weight: 30
  #- name: Teaching
  #  url: teaching/
  #  weight: 40
  
header:
  navbar:
    # Display the navigation bar?
    enable: true
    # Choose a built-in navigation blox or create your own
    blox: "navbar"
    # Align menu links: `left`, `center`, or `right`
    align: "right"
    # Fix the navigation bar to the top of the page
    fixed_to_top: true
    # Let the user choose between light or dark mode?
    show_theme_chooser: true
    # Let the user search from the navigation bar?
    show_search: false
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true